name: Duplicater

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *' # JST 6:00

env:
  SID: ${{ secrets.SID }}
  PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
  SOURCE_PROJECT_NAME: ${{ secrets.SOURCE_PROJECT_NAME }}
  DESTINATION_PROJECT_NAME: ${{ secrets.DESTINATION_PROJECT_NAME }}
  SHOULD_DUPLICATE_BY_DEFAULT: ${{ secrets.SHOULD_DUPLICATE_BY_DEFAULT }}

jobs:
  build:
    permissions:
      contents: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run duplicator
        run: bun index.ts
