name: update-bun-dependencies

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Update dependencies
        run: bun update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: ':arrow_up: update bun dependencies'
          title: Update Bun Dependencies
          body: >
            Automated updates by `bun update`
            and [create-pull-request](https://github.com/peter-evans/create-pull-request)
            GitHub action
          branch: update-bun-dependencies
          author: GitHub <noreply@github.com>
          delete-branch: true
